// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycledRushRobot.commands;

import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc692.RecycledRushRobot.Robot;
import org.usfirst.frc692.RecycledRushRobot.RobotConstant;
import org.usfirst.frc692.RecycledRushRobot.RobotMap;

/**
 *
 */
public class  DriveWithGyro extends Command {

    public DriveWithGyro() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    	//RobotMap.driveTraingyro.reset();
    	//SmartDashboard.putNumber("Gyro Angle Init:", RobotMap.driveTraingyro.getAngle());
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	double x = Robot.oi.driveJoystick.getX();
    	double y = Robot.oi.driveJoystick.getY();
    	double rotation = Robot.oi.driveJoystick.getZ() * 0.5;
    	double gyroAngle = RobotMap.driveTraingyro.getAngle() * (RobotConstant.GyroMultiplier * -1.0);
    	//SmartDashboard.putNumber("Gyro Angle Testing:", gyroAngle);
    	//SmartDashboard.putNumber("Rotation Value:", Robot.oi.driveJoystick.getZ());
    	
    	//double xinvert = x * -1.0;
    	//double yinvert = y * -1.0;
    	//double zinvert = rotation * -1.0;
    	//made inverted variables just in case
    	//EV 1/16/2015
    	//SmartDashboard.putNumber("Rotation Value Before:", rotation);
    	/*
    	if (rotation >= 0.0 && rotation < 0.3)
    		rotation = 0.0;
    	else if (rotation <= 0.0 && rotation > -0.3)
    		rotation = 0.0;
    		*/
    	/*
    	else if (rotation >= 0.3)
    		rotation = rotation - 0.2;
    	else if (rotation <= -0.3)
    		rotation = rotation + 0.2;
    		*/
    	// creates a deadspace / "wiggle room" for the twist of the joystick
    	// EV 1/31/2015
    	//SmartDashboard.putNumber("Rotation Value After:", rotation);
    	Robot.driveTrain.takeJoystickValueGyro(x, y, rotation, gyroAngle);
    	// takes the new values and put them in for method
    	// EV 1/16/2015 	
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
