// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycledRushRobot.subsystems;

import org.usfirst.frc692.RecycledRushRobot.Robot;
import org.usfirst.frc692.RecycledRushRobot.RobotMap;
import org.usfirst.frc692.RecycledRushRobot.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class RollyGrabber extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController rollyGrabberMotorOne = RobotMap.rollyGrabberrollyGrabberMotorOne;
    SpeedController rollyGrabberMotorTwo = RobotMap.rollyGrabberrollyGrabberMotorTwo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
    public void takeJoystickAxisValue(double x)
    {
    	rollyGrabberMotorOne.set(-x);
    	rollyGrabberMotorTwo.set(x);
    }
    // takes value from joystick and inputs in rolly grabber motors
    // AC 1/24/15
    
    public void rollyGrabberGo()
    {
    	rollyGrabberMotorOne.set(-1.0);
    	rollyGrabberMotorTwo.set(1.0);
    }
    // sets sets rolly grabber motors at full power
    // AC 1/31/15
    
    public void rollyGrabberStop()
    {
    	rollyGrabberMotorOne.set(0.0);
    	rollyGrabberMotorTwo.set(0.0);
    }
    
    public void rollyGrabberReverse()
    {
    	rollyGrabberMotorOne.set(1.0);
    	rollyGrabberMotorTwo.set(-1.0);
    }
}

