// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc692.RecycledRushRobot;

import org.usfirst.frc692.RecycledRushRobot.commands.AutonDrive;
import org.usfirst.frc692.RecycledRushRobot.commands.*;

import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// CREATING BUTTONS
    // One type of button is a joystick button which is any button on a joystick.
    // You create one by telling it which joystick it's on and which button
    // number it is.
    // Joystick stick = new Joystick(port);
    // Button button = new JoystickButton(stick, buttonNumber);
    
    // There are a few additional built in buttons you can use. Additionally,
    // by subclassing Button you can create custom triggers and bind those to
    // commands the same as any other Button.
    
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton buttonOneRollyGrabberTest;
    public JoystickButton buttonOneRollyGrabbersStop;
    public JoystickButton buttonTwoManualElevatorDown;
    public JoystickButton buttonTwoElevatorStop;
    public JoystickButton buttonThreeManualElevator;
    public JoystickButton buttonThreeElevatorStop;
    public JoystickButton buttonFourCaterpillarBack;
    public JoystickButton buttonFourCaterpillarStop;
    public JoystickButton buttonFiveCaterpillarForward;
    public JoystickButton buttonFiveCaterpillarStop;
    public JoystickButton buttonSevenCaterpillarStop;
    public JoystickButton buttonTenFlapping;
    public JoystickButton buttonElevenReverseFlapping;
    public Joystick manualStick;
    public JoystickButton buttonOneDispenseAtStep;
    public JoystickButton buttonTwoDispenseAtGround;
    public JoystickButton buttonThreeGatherTote;
    public JoystickButton buttonFourEmergencyStopCycle;
    public JoystickButton buttonFivePickUpRecycleBin;
    public JoystickButton buttonSixDropRBAtZeroTotes;
    public JoystickButton buttonSevenDropRBatOneTote;
    public JoystickButton buttonEightDropRBatTwoTotes;
    public JoystickButton buttonNineDropRBatThreeTotes;
    public JoystickButton buttonTenDropRBatFourTotes;
    public JoystickButton buttonElevenDropRBatFiveTotes;
    public JoystickButton buttonTwelveDropRBatSixTotes;
    public Joystick autoStick;
    public JoystickButton driveForward;
    public JoystickButton driveBackward;
    public JoystickButton driveLeft;
    public JoystickButton driveRight;
    public JoystickButton emergencyStop;
    public JoystickButton withoutGyroButton;
    public JoystickButton withGyro;
    public JoystickButton resetGy;
    public Joystick driveJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        driveJoystick = new Joystick(2);
        
        resetGy = new JoystickButton(driveJoystick, 2);
        resetGy.whenPressed(new resetGyro());
        withGyro = new JoystickButton(driveJoystick, 6);
        withGyro.whenPressed(new DriveWithGyro());
        withoutGyroButton = new JoystickButton(driveJoystick, 4);
        withoutGyroButton.whenPressed(new DriveWithoutGyro());
        emergencyStop = new JoystickButton(driveJoystick, 10);
        emergencyStop.whenPressed(new DriveStopAuto());
        driveRight = new JoystickButton(driveJoystick, 12);
        driveRight.whileHeld(new driveRightAuton());
        driveLeft = new JoystickButton(driveJoystick, 11);
        driveLeft.whileHeld(new driveLeftAuton());
        driveBackward = new JoystickButton(driveJoystick, 3);
        driveBackward.whileHeld(new DriveBackwardAuto());
        driveForward = new JoystickButton(driveJoystick, 5);
        driveForward.whileHeld(new DriveForwardAuto());
        autoStick = new Joystick(1);
        
        buttonTwelveDropRBatSixTotes = new JoystickButton(autoStick, 12);
        buttonTwelveDropRBatSixTotes.whenPressed(new dropTrashCanAtSix());
        buttonElevenDropRBatFiveTotes = new JoystickButton(autoStick, 11);
        buttonElevenDropRBatFiveTotes.whenPressed(new dropTrashCanAtFive());
        buttonTenDropRBatFourTotes = new JoystickButton(autoStick, 10);
        buttonTenDropRBatFourTotes.whenPressed(new dropTrashCanAtFour());
        buttonNineDropRBatThreeTotes = new JoystickButton(autoStick, 9);
        buttonNineDropRBatThreeTotes.whenPressed(new dropTrashCanAtThree());
        buttonEightDropRBatTwoTotes = new JoystickButton(autoStick, 8);
        buttonEightDropRBatTwoTotes.whenPressed(new dropTrashCanAtTwo());
        buttonSevenDropRBatOneTote = new JoystickButton(autoStick, 7);
        buttonSevenDropRBatOneTote.whenPressed(new dropTrashCanAtOne());
        buttonSixDropRBAtZeroTotes = new JoystickButton(autoStick, 6);
        buttonSixDropRBAtZeroTotes.whenPressed(new dropTrashCanAtZero());
        buttonFivePickUpRecycleBin = new JoystickButton(autoStick, 5);
        buttonFivePickUpRecycleBin.whenPressed(new pickUpRecycleBin());
        buttonFourEmergencyStopCycle = new JoystickButton(autoStick, 4);
        buttonFourEmergencyStopCycle.whenPressed(new ermergencyStopCycle());
        buttonThreeGatherTote = new JoystickButton(autoStick, 3);
        buttonThreeGatherTote.whenPressed(new gatherTote());
        buttonTwoDispenseAtGround = new JoystickButton(autoStick, 2);
        buttonTwoDispenseAtGround.whenPressed(new dispenseTotesAtGround());
        buttonOneDispenseAtStep = new JoystickButton(autoStick, 1);
        buttonOneDispenseAtStep.whenPressed(new dispenseAtStep());
        manualStick = new Joystick(0);
        
        buttonElevenReverseFlapping = new JoystickButton(manualStick, 11);
        buttonElevenReverseFlapping.whenPressed(new reverseFlap());
        buttonTenFlapping = new JoystickButton(manualStick, 10);
        buttonTenFlapping.whenPressed(new flapping());
        buttonSevenCaterpillarStop = new JoystickButton(manualStick, 7);
        buttonSevenCaterpillarStop.whenPressed(new caterpillarStop());
        buttonFiveCaterpillarStop = new JoystickButton(manualStick, 5);
        buttonFiveCaterpillarStop.whenReleased(new caterpillarStop());
        buttonFiveCaterpillarForward = new JoystickButton(manualStick, 5);
        buttonFiveCaterpillarForward.whileHeld(new caterpillarForward());
        buttonFourCaterpillarStop = new JoystickButton(manualStick, 4);
        buttonFourCaterpillarStop.whenReleased(new caterpillarStop());
        buttonFourCaterpillarBack = new JoystickButton(manualStick, 4);
        buttonFourCaterpillarBack.whileHeld(new caterpillarBackward());
        buttonThreeElevatorStop = new JoystickButton(manualStick, 3);
        buttonThreeElevatorStop.whenReleased(new elevatorStop());
        buttonThreeManualElevator = new JoystickButton(manualStick, 3);
        buttonThreeManualElevator.whileHeld(new elevatorUpWithoutLimitSwitch());
        buttonTwoElevatorStop = new JoystickButton(manualStick, 2);
        buttonTwoElevatorStop.whenReleased(new elevatorStop());
        buttonTwoManualElevatorDown = new JoystickButton(manualStick, 2);
        buttonTwoManualElevatorDown.whileHeld(new elevatorDownWithoutLimitSwitch());
        buttonOneRollyGrabbersStop = new JoystickButton(manualStick, 1);
        buttonOneRollyGrabbersStop.whenReleased(new rollyGrabberStop());
        buttonOneRollyGrabberTest = new JoystickButton(manualStick, 1);
        buttonOneRollyGrabberTest.whileHeld(new rollyGrabbersGo());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("AutonDriveBackward", new AutonDriveBackward());

        SmartDashboard.putData("AutonDriveForward", new AutonDriveForward());

        SmartDashboard.putData("AutonGroup", new AutonGroup());

        SmartDashboard.putData("AutonDrive", new AutonDrive());

        SmartDashboard.putData("DriveTurnAroundAuton", new DriveTurnAroundAuton());

        SmartDashboard.putData("DriveTurnNinetyDegreesAuton", new DriveTurnNinetyDegreesAuton());

        SmartDashboard.putData("DriveWithGyro", new DriveWithGyro());

        SmartDashboard.putData("DriveWithoutGyro", new DriveWithoutGyro());

        SmartDashboard.putData("DriveBackwardAuto", new DriveBackwardAuto());

        SmartDashboard.putData("DriveForwardAuto", new DriveForwardAuto());

        SmartDashboard.putData("driveLeftAuton", new driveLeftAuton());

        SmartDashboard.putData("driveRightAuton", new driveRightAuton());

        SmartDashboard.putData("DriveStopAuto", new DriveStopAuto());

        SmartDashboard.putData("resetGyro", new resetGyro());

        SmartDashboard.putData("automatedElevator", new automatedElevator());

        SmartDashboard.putData("bringInToteOnCaterpillar", new bringInToteOnCaterpillar());

        SmartDashboard.putData("reverseFlap", new reverseFlap());

        SmartDashboard.putData("caterpillarStop", new caterpillarStop());

        SmartDashboard.putData("caterpillarBackward", new caterpillarBackward());

        SmartDashboard.putData("caterpillarControlWithJoystick", new caterpillarControlWithJoystick());

        SmartDashboard.putData("dispenseTotesAtGround", new dispenseTotesAtGround());

        SmartDashboard.putData("manualRecycleBinClaw", new manualRecycleBinClaw());

        SmartDashboard.putData("gatherTote", new gatherTote());

        SmartDashboard.putData("dropTrashCanAtZero", new dropTrashCanAtZero());

        SmartDashboard.putData("dropTrashCanAtOne", new dropTrashCanAtOne());

        SmartDashboard.putData("dropTrashCanAtTwo", new dropTrashCanAtTwo());

        SmartDashboard.putData("dropTrashCanAtThree", new dropTrashCanAtThree());

        SmartDashboard.putData("dropTrashCanAtFour", new dropTrashCanAtFour());

        SmartDashboard.putData("dropTrashCanAtFive", new dropTrashCanAtFive());

        SmartDashboard.putData("dropTrashCanAtSix", new dropTrashCanAtSix());

        SmartDashboard.putData("dispenseAtStep", new dispenseAtStep());

        SmartDashboard.putData("resetToteCycle", new resetToteCycle());

        SmartDashboard.putData("elevatorGoToStepLevel", new elevatorGoToStepLevel());

        SmartDashboard.putData("elevatorGoToGroundLevel", new elevatorGoToGroundLevel());

        SmartDashboard.putData("elevatorGoToTopLevel", new elevatorGoToTopLevel());

        SmartDashboard.putData("caterpillarForward", new caterpillarForward());

        SmartDashboard.putData("elevatorUpWithoutLimitSwitch", new elevatorUpWithoutLimitSwitch());

        SmartDashboard.putData("elevatorDownWithoutLimitSwitch", new elevatorDownWithoutLimitSwitch());

        SmartDashboard.putData("rollyGrabbersGo", new rollyGrabbersGo());

        SmartDashboard.putData("elevatorStop", new elevatorStop());

        SmartDashboard.putData("resetFlapper", new resetFlapper());

        SmartDashboard.putData("elevatorTakeJoystickValie", new elevatorTakeJoystickValie());

        SmartDashboard.putData("pickUpRecycleBin", new pickUpRecycleBin());

        SmartDashboard.putData("recycleBinClawOpen", new recycleBinClawOpen());

        SmartDashboard.putData("recycleBinClawBottom", new recycleBinClawBottom());

        SmartDashboard.putData("rollyGrabberTest", new rollyGrabberTest());

        SmartDashboard.putData("rollyGrabberControl", new rollyGrabberControl());

        SmartDashboard.putData("winchAtZeroTotes", new winchAtZeroTotes());

        SmartDashboard.putData("rollyGrabberStop", new rollyGrabberStop());

        SmartDashboard.putData("ermergencyStopCycle", new ermergencyStopCycle());

        SmartDashboard.putData("winchAtOneTote", new winchAtOneTote());

        SmartDashboard.putData("winchAtTwoTotes", new winchAtTwoTotes());

        SmartDashboard.putData("winchAtThreeTotes", new winchAtThreeTotes());

        SmartDashboard.putData("winchAtFourTotes", new winchAtFourTotes());

        SmartDashboard.putData("winchAtFiveTotes", new winchAtFiveTotes());

        SmartDashboard.putData("winchAtSixTotes", new winchAtSixTotes());

        SmartDashboard.putData("recycleBinClawUp", new recycleBinClawUp());

        SmartDashboard.putData("flapping", new flapping());

        SmartDashboard.putData("recycleBinClawClose", new recycleBinClawClose());

        SmartDashboard.putData("reverseCaterpillar", new reverseCaterpillar());


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getmanualStick() {
        return manualStick;
    }

    public Joystick getautoStick() {
        return autoStick;
    }

    public Joystick getDriveJoystick() {
        return driveJoystick;
    }


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
}

